### ISSUE TITLE
Version 0.1 certification pass

### ISSUE THREAD

**Issue by danielmarschall** [frdl/oidplus-frdlweb-rdap#21]
Hallo Till,
Commit 4e0badd hat alle Punkte der vorläufigen Zertifizierung bestanden!
Es kann nun mit deinem Einverständnis in das offizielle OIDplus-Release eingebaut werden.

Ich erweitere die Zertifizierung in den nächsten Tagen nochmal und führe den Testcase "PHP 8.1" und "Microsoft SQL Server mit IIS" ein, aber ich denke das besteht dein Plugin auch.

Das Plugin wird sich natürlich weiterentwickeln (besonders weil das RDAP Schema ja noch nicht 100% fest steht), und die Weiterentwicklung soll in diesem GitHub-Repo erfolgen. Ich möchte daher Dinge wie Code-Formatierung gerne hier direkt an der Quelle vornehmen, nicht erst in meinem SVN. Denn dann kann man im Idealfall einfach nur das GitHub Repo nehmen kann und in OIDplus einspielen, ohne dass ich noch irgendwelche Anpassungen bei jedem upstream-Update durchführen muss.
Wie machen wir das am besten? Ich bin mit GIT gar nicht fit

Viele Grüße
Daniel

**Comment by wehowski** [comment]
> Wie machen wir das am besten? Ich bin mit GIT gar nicht fit
* Composer + ein "oidplus-composer-plugin" und package type "oidplus-plugin". (Vielleicht für spätere Versionen?)
* Oder einfacher zunächst: Die Verzeichnis Struktur entspricht der des OIDplus, das Plugin ist in einem "plugin" Unterverzeichnis, theoretisch wäre es "safe" das Archiv Downzuloaden und einfach im OIDplus root zu entpacken? Das geht auch automatisiert z.B. mit php. Du kannst für das Github Repository Releases erstellen und die Entwicklung in "branches" splitten. Jeder Branch/release/commit... hat ein Archiv-download-link, ich meine als .zip und .,tar.gz welchen Du entsprechend in Deinen OIDplus Versionen verwenden kannst (oder halt nur einen Master-Baum)!?
Z.b. (ich glaube das ist nicht aktuell notwendig für das Plugin!?!) könntest Du einen "master-php7" und einen "master-php8" Branch erstellen und je nach verwendeter Version in der Instanz runterladen und entpacken. Falls es z.B. zwangsläufige Inkompatibilitäten zwischen den PHP-Versionen geben sollte, usw...
Da gibts tausend Wege wie Du das gestalten kannst.

Viele Grüße
Till

**Comment by wehowski** [comment]
Ich habe Deine Rolle auf "Admin" geändert.

**Comment by danielmarschall** [comment]
Ich würde das gar nicht so kompliziert machen mit branches und so. Ich will einfach dass das GitHub runtergeladen werden kann, und dann direkt in OIDplus rein, ohne dass noch Anpassungen vorgenommen werden müssen. Ich weis aber nicht wie man mit Git arbeitet und ich will nix kaputt machen.

**Comment by danielmarschall** [comment]
Der Testcase PHP 8.1 + MSSQL + IIS ist auch erfolgreich gewesen

**Comment by danielmarschall** [comment]
GIT Commit [cb8d3f7](https://github.com/frdl/oidplus-frdlweb-rdap/commit/cb8d3f77d4f36b01972ef3de377cf8a44ccaf497) ist nun [zertifiziert](https://1drv.ms/w/s!Aq8PcXiGvLchhadJ3Ums6jdSjHb2gQ) und veröffentlicht in OIDplus SVN Revision 939.

Von nun ab werden dann in regelmäßigen Abständen dieses GIT Repo in das offizielle OIDplus Verzeichnis synchronisiert.

Bitte setze einen Tag und Release als "Version 0.1" auf cb8d3f7 (ich weiß nicht wie man das auf der Webseite hier macht, vielleicht zeigst du mir das mal mit einem Screenshot per E-Mail)
Danach kann dieses Ticket geschlossen werden

**Comment by wehowski** [comment]
Hallo Daniel,
habe Dir eine Mail geschrieben.
