### ISSUE TITLE
OID-IP inclusion with password protected public URL

### ISSUE THREAD

**Issue by danielmarschall** [frdl/oidplus-frdlweb-rdap#23]
There are two instances with `file_get_contents` which access the OID-IP service.

Please support the case that `file_get_contents` can fail (e.g. if OIDplus is located on a password-protected system). Otherwise you will get a PHP error message which invalidates the JSON format.

Not sure what we can do if file_get_contents() cannot access the own directory, though.

**Comment by danielmarschall** [comment]
Fixed: Added @ in front of file_get_contents
If file_get_contents is false, then solely the link to the OID-IP URL is shown, so the user can click it and enter the password.

**Comment by wehowski** [comment]
The webhois can also handle cli calls? Maybe it would make more sense to use exec/shell_exec rather than file_get_contents?
Edit: I am not sure if this is expected to be supported by every host? On our testserver it should be enabled.

**Comment by danielmarschall** [comment]
Yes, it can be called by CLI.

Actually, this is a good idea, but I would even solve it in a more elegant way:

TODO: In RDAP and WHOIS, instead of putting the whole code in webwhois.php or rdap.php , put the whole code in a PHP function of the PHP class, so that webwhois.php and rdap.php only need to call `OIDplusXXX::oid_whois($query)`.  The same thing was already done with `oidinfo_export.php`.

I will do that ASAP.
