### ISSUE TITLE
Caching using serialize/unserialize

### ISSUE THREAD

**Issue by danielmarschall** [frdl/oidplus-frdlweb-rdap#27]
I was just looking at the caching functions, and I wonder why do you do it so complicated?!
You create a PHP file whose purpose it is to return a variable. Then you execute the script to read the variable.

```
	protected function rdap_write_cache($out, $cacheFile){
		if(!is_string($cacheFile)){
			return;
		}
		$exp = var_export($out, true);
		$code = <<<PHPCODE
<?php
 return $exp;
PHPCODE;

		file_put_contents($cacheFile, $code);
		touch($cacheFile);
	}

	protected function rdap_read_cache($cacheFile, $rdapCacheExpires){
		if(is_string($cacheFile) && file_exists($cacheFile) && filemtime($cacheFile) >= time() - $rdapCacheExpires ){
			$out = include $cacheFile;
			if(is_array($out) || is_object($out)){
				return $this->rdap_out($out);
			}
		}
		return null;
	}
```

Why not just read and write the contents, serialized?? And you don't need `touch` when you just wrote using `file_put_contents`.

```
	protected function rdap_write_cache($out, $cacheFile){
		if (!is_string($cacheFile)) return;
		file_put_contents($cacheFile, serialize($out));
	}

	protected function rdap_read_cache($cacheFile, $rdapCacheExpires){
		if (is_string($cacheFile) && file_exists($cacheFile) && filemtime($cacheFile) >= time() - $rdapCacheExpires) {
			$out = unserialize(file_get_contents($cacheFile));
			if(is_array($out) || is_object($out)){
				return $this->rdap_out($out);
			}
		}
		return null;
	}
```

**Comment by danielmarschall** [comment]
Also, just serializing is more safe, because including a PHP file can be very dangerous, especially because you placed the PHP file in a temp directory which might be world-writeable by some systems (Windows?).

**Comment by wehowski** [comment]
Hello Daniel,
I do not find it "complicated", the var_export and $value = include pattern, in my opinion is the FASTEST cache in READ context, and I "just like" it.
But I agree with that serializing is much safer when it comes to user input. 
The cached variable is (de)serialized by the get from whois script, I thought it would be safe enough to use the var_export method.
But we can change it to serialize if you feel better with it!

P.S.: Ich komme gegen Nachmittag/Abend dazu mir alle neuen Beiträge in Ruhe durchgelesen zu haben...

EDIT: You can change the temp directory by config.
