### ISSUE TITLE
Verknüpfung mit Alt-ID Plugin

### ISSUE THREAD

**Issue by danielmarschall** [frdl/oidplus-frdlweb-rdap#28]
Mir ist aufgefallen, dass du die alt_ids Tabelle nur um einen Datensatz abfrägst, aber was ist wenn ein Objekt mehrere Alt-IDs hat?

Ich würde folgende Änderung vorschlagen, nun nach dem die Funktion `OIDplusPagePublicObjects::getAlternativesForQuery` für das [Alt-ID-Plugin erschaffen wurde](https://github.com/frdl/oidplus-plugin-alternate-id-tracking/issues/8):

Vorschlag:

1. Entferne den bisherigen Code für alt_id komplett
2. Iteriere stattdessen durch die Ausgaben von `OIDplusPagePublicObjects::getAlternativesForQuery` wenn `$obj==null`. Das mit dem `$obj==null` ist mir wichtig, denn wenn das angesprochene Objekt vorhanden ist, dann hat dieses unbedingt Vorrang, selbst wenn es als AltID in einem anderem Objekt referenziert ist

Was meisnt du?

**Comment by danielmarschall** [comment]
In a3141585db5b6c19be9a1703f4c12af88060e8e4 wurde die Datenbankreferenz einen anderen Code ersetzt.
(Ich verstehe aber nicht ganz, wo `getCanonicalStatic` definiert ist?)

**Comment by wehowski** [comment]
getCanonicalStatic ist hier "magisch" definiert: https://github.com/frdl/oidplus-plugin-alternate-id-tracking/blob/main/plugins/frdl/publicPages/altids/OIDplusPagePublicAltIds.class.php#L23
OIDPlus bevorzugt oft statische Methoden/Classen (?), ich eigentlich weiß nicht genau, deshalb habe ich das hier flexibel gemacht.

**Comment by danielmarschall** [comment]
Ich habe einige Verständnisprobleme...

1. Was ist der Grund für dieses Static? Sowas wird doch OIDplus nirgends gemacht?

2. Wieso rufst du nicht `OIDplusPagePublicObjects::getAlternativesForQuery` auf? `getCanonical()` gibt dir ja immer nur eine OID aus. Also "AID" wird zu "OID". Aber es geht nicht wenn man von "OID" zu "AID" möchte.

**Comment by wehowski** [comment]
2. Im Context vom RDAP Plugin würde eine Endlos-Umleitung entstehen können? 
    Ich habe angenommen, dass von den getAlternativesForQuery Ids die oid: wahrscheinlich als "kanonischer Eintrag" vorhanden ist, vielleicht sollte ich das nochmal überdenken?
1. Meinst Du ich soll getAlternativesForQuery  und getCanonical lieber als statische Methoden definieren?

**Comment by danielmarschall** [comment]
Ich habe gerade gesehen, dass `getAlternativesForQuery` in plugins/viathinksoft/publicPages/000_objects/OIDplusPagePublicObjects.class.php als `private` gelistet ist.
Ich glaube das ist nicht richtig. Ich muss das zu `public` machen.

Der Sinn dahinter:
`OIDplusPagePublicObjects::getAlternativesForQuery()` ruft die Funktion OIDplusPagePublicObjects() von allen Plugins auf, die das Feature "1.3.6.1.4.1.37476.2.5.2.3.7" implementieren.
Wichtig ist, dass `OIDplusPagePublicObjects` _**nicht**_ das Feature implementiert, da es sonst eine Endlosschleife gäbe.
Die Funktion `getAlternativesForQuery` eines Plugins sollte nicht direkt angesprochen werden, sondern immer `OIDplusPagePublicObjects::getAlternativesForQuery()` als zentrale Anlaufstelle / Verteiler.

**Comment by danielmarschall** [comment]
`OIDplusPagePublicObjects::getAlternativesForQuery()` ist nun public:
https://github.com/danielmarschall/oidplus/commit/84f871698171080bfef9f80d9f88a53efa4e59e6

**Comment by danielmarschall** [comment]
Noch eine Änderung: https://github.com/danielmarschall/oidplus/commit/0e2b7179d33ff83a01d2c4e6cd3d46c1b9ab24e6
`OIDplusPagePublicObjects::getAlternativesForQuery($id)` sorgt nun dafür, dass in der Ausgabe der Wert `$id` **_nicht_** enthalten ist [falls ein Plugin das falsch macht]. Denn es ist ja eine Liste der alternativen Identifier, und der eigene Identifier ist ja kein alternativer.

**Comment by danielmarschall** [comment]
Ich habe in af4d951d2ce32b309a52b5d25206bf5501a648fa das mal so gemacht, wie ich mir das vorgestellt habe. Bitte prüfe mal, ob das so funktioniert.

**Comment by danielmarschall** [comment]
(Vorsicht: Es hat eine Änderung am System gegeben. Bitte OIDplus zuerst updaten. Habe RDAP Version 0.3 veröffentlicht und mit dem System ausgeliefert, damit keine Inkompatibilität zwischen Plugin und System entsteht)

**Comment by wehowski** [comment]
Hallo Daniel,
Danke!!!

Etwas hakt bei  mir noch beim RDAP und custom Object Types. Möglicherweise wurde das Update nicht korrekt ausgeführt oder ich hab in den Types einen Fehler?
[Whois geht](https://registry.frdl.de/plugins/viathinksoft/publicPages/100_whois/whois/webwhois.php?query=guid:6a35a4d5-ff00-35ad-a42f-e54d6fbc4d31) | [RDAP geht nicht](https://registry.frdl.de/plugins/frdl/publicPages/1276945_rdap/rdap/rdap.php?query=guid:6a35a4d5-ff00-35ad-a42f-e54d6fbc4d31) | [Page geht](https://registry.frdl.de/?goto=guid:6a35a4d5-ff00-35ad-a42f-e54d6fbc4d31)

**Comment by danielmarschall** [comment]
Hallo Till,
folgende Änderung ist erforderlich:

```
		$obj = OIDplusObject::findFitting($query);
		//if (!$obj) $obj = OIDplusObject::parse($query);
		if ($obj) $query = $obj->nodeId();
```

(!$obj) wird nicht erfüllt, da der Dateityp "guid" existiert...
ich muss prüfen, ob das jetzt irgendwelche negativen Auswirkungen hat, und ob das in OID-IP auch notwendig ist.

Ich habe den Cache auskommentiert, weil das für das Debuggen sehr frustrierend ist :)

**Comment by danielmarschall** [comment]
Bitte probiere, ob damit alles funktioniert

**Comment by wehowski** [comment]
...ja, der [Testlink von oben geht jetzt](https://registry.frdl.de/plugins/frdl/publicPages/1276945_rdap/rdap/rdap.php?query=guid:6a35a4d5-ff00-35ad-a42f-e54d6fbc4d31).

P.S.: Ein neuer Benutzer hat sich hinzugesellt: https://registry.frdl.de/?goto=oid%3A1.3.6.1.4.1 Allerdings gab es wohl bei der invite-Bestätigung Schwierigkeiten, und eine Fehlermeldung...

**Comment by danielmarschall** [comment]
Fixed in version 0.3.1, bunded with OIDplus SVN Revision 972
