### ISSUE TITLE
.htaccess file for internal redirect / HTTP404-Detection API

### ISSUE THREAD

**Issue by danielmarschall** [frdl/oidplus-frdlweb-rdap#3]
In the root directory (where README.md and LICENSE is located) we should also put a `.htaccess` that does the Apache2 `mod_rewrite` stuff to redirect `/oid/2.999` to `plugins/..../rdap.php` .

If possible, also include a file for nginx.

**Comment by wehowski** [comment]
Suggestion: We should provide something like a .htaccess "generator" or plugin, which generates the .htaccess/nginx file dynamically, as this could vary from instance to instance. 
The /oid/ Slug could be any slug wich is not a physical directory, or (like mentioned above) ist should be /(oid|weid|java)/ for example, regarding the installed Object Types.
???

**Comment by danielmarschall** [comment]
This sounds interesting. Indeed, the problem is that the .htaccess would need to be renewed if new object type plugins are installed.

Another possible idea :
We could have a .htaccess which handles all HTTP requests and sends them to a resolve PHP script. This script decides what to do (and can be influenced by the page plugins).
But accessing static resources like PNG files or CSS files would be very hard with this approach, because we would "re-invent the wheel" (implement Content-Type, E-Tag, etc.)?!

**Comment by wehowski** [comment]
> Another possible idea : We could have a .htaccess which handles all HTTP requests and sends them to a resolve PHP script. 
> This script decides what to do (and can be influenced by the page plugins).

That sounds like a typical task for a "Router" Class/Library. There are existing classes out there, I suggest to choose one of the well known solutions. A Plugin could register its own "routes".

> But accessing static resources like PNG files or CSS files would be very hard with this approach, because we would "re-invent > the wheel" (implement Content-Type, E-Tag, etc.)?!

In Apache you can skip existing files/dirs for mod_rewrite:
````
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d 
````
Ngnix is made/optimized to serve the static files and pass dynamic script requests to Apache, thats how common configs works on my servers.

**Comment by danielmarschall** [comment]
I totally forgot about `-f` and `-d` .

Ok, then I will do the following:
- OIDplus will redirect those 404 to a handler script (the handler script must be able to know the file that was tried to access)
- The handler script will handle this 404 . It will ask the plugins if they know what to do. If no plugin knows what to do, then a custom 404 page is shown.

Can you please provide me with the nginx config file that does the same as Apache's RewriteCond?
I will search for the MS IIS web.config possibility.

**Comment by wehowski** [comment]
Hello Daniel,
I am not used to nginx, I must use google.
This is what I found for router file: https://stackoverflow.com/questions/26093270/nginx-how-to-let-rewrite-rules-ignore-files-or-folders
For !-f and !-d I found `try_files`, but never used it in production for my self: https://stackoverflow.com/questions/12206560/converting-apache-rewrite-rules-to-an-nginx-config-file
(The only server I am using without apache in production is my CDN Server. There is an Option in Plesk "Apache&Ngnix rules where you can set options like to serve static files by apache or ngnix, maybe I can find the generated config files, I will look...)

**Comment by danielmarschall** [comment]
TODO @danielmarschall :
- Implement "HTTP 404" handler in the OIDplus system and let plugins interchange with it
  (for now just Apache2)
- Make use of API in the RDAP plugin

**Comment by danielmarschall** [comment]
In the next release of OIDplus (SVN Rev >= 946), we will have a "handle404" API function.
Currently, it is only supported with Apache2 (.htaccess).

This is what I would like to add to `OIDplusPagePublicRdap`:

```
	public function handle404($request) {
		$namespaces = array();
		foreach (OIDplus::getEnabledObjectTypes() as $ot) {
			$namespaces[] = $ot::ns();
		}

		foreach ($namespaces as $ns) {
			// Note: This only works if OIDplus is located at the domain root (because $request is relative to the domain)
			if (!preg_match('@^/'.preg_quote($ns,'@').'/(.+)$@', $request, $m)) return false;
			$oid = $m[1];
			$query = "$ns:$oid";
			$x = new OIDplusRDAP();
			list($out_content, $out_type) = $x->rdapQuery($query);
			if ($out_type) header('Content-Type:'.$out_type);
			echo $out_content;
			die(); // return true;
		}
	}
```

Is this OK?

**Comment by wehowski** [comment]
Hi Daniel,
this is nice, but I would prefer to register a "regular" router rather than a 404 handler, as the 404 indicates not found.
You can register the routes by core and/or allow plugins to register their own routes.
There are many php routers available, e.g. the symfony router or [google](https://www.google.com/search?q=php+router&rlz=1C1CHBD_deDE977DE977&oq=php+router&aqs=chrome..69i57j0i512l3j0i22i30l3j69i60.2839j0j7&sourceid=chrome&ie=UTF-8), this is one of my favorites: https://altorouter.com/
With a router you can provide "pretty urls", the 404 handler is more like a "work around"?

**Comment by danielmarschall** [comment]
Sorry, I don’t want to introduce more dependencies and frameworks into the product. Plus, I do not have any knowledge about this topic, so introducing such a framework into the product will most likely be counterproductive.

**Comment by danielmarschall** [comment]
Also, I DO want to have RDAP only work on 404 requests. Otherwise, you can break your system, e.g. by installing a object type plugin with the namespace “img” or “plugins” or “setup”. Then, RDAP would be opened instead of the folders, and your system is damaged.

**Comment by danielmarschall** [comment]
Implemented 404 handler for Microsoft IIS (OIDplus system SVN Rev 947, tested)

Implemented 404 handler for NGINX (OIDplus system SVN Rev 948, tested with docker for Windows, container trafex/php-nginx)
